image: smartbcity/gitlab-ci-kotlin-all:latest

stages:
  - version
  - package

variables:
  BRANCH_VERSION: "experimental-SNAPSHOT"
  MASTER_VERSION: "next-SNAPSHOT"
  PROFILES_ACTIVE: "gitlab"

.version:
  stage: version
  image: smartbcity/gitlab-ci-semantic-versioning:latest
  script:
    - make -f /opt/city.smartb/semantic-versioning/Makefile next_version >> version.build
  artifacts:
    paths:
      - version*

.version_dev:
  extends: .version
  after_script:
    - echo $DEV_VERSION > version.build
    - echo "//////////////////////////////"
    - echo "Version is " $(cat version.build)
    - echo "//////////////////////////////"

.package:
  stage: package
  script:
    - export VERSION_BUILD=$(cat version.build)
    - make package -e VERSION=${VERSION_BUILD}

.onlyBranch: &onlyBranch
  only:
    refs:
      - branches
  except:
    refs:
      - master

.onlyMaster: &onlyMaster
  only:
    refs:
      - master

.onlyTags: &onlyTags
  only:
    - tags

version-branch:
  <<: *onlyBranch
  stage: version
  variables:
    DEV_VERSION: $BRANCH_VERSION
  extends: .version_dev

package-branch:
  <<: *onlyBranch
  extends: .package
  artifacts:
    paths:
      - version*

version-master:
  <<: *onlyMaster
  stage: version
  variables:
    DEV_VERSION: $MASTER_VERSION
  extends: .version_dev

package-master:
  <<: *onlyMaster
  extends: .package
  artifacts:
    paths:
      - version*

version-tags:
  <<: *onlyTags
  extends: .version

package-tags:
  <<: *onlyTags
  extends: .package