spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost/admin
      auto-index-creation: true

ssm:
  signer:
    user:
      name: adam
      key: user/adam
    admin:
      name: ssm-admin
      key: user/adam
  couchdb:
    url: http://localhost:5984
    username: couchdb
    password: couchdb
    serviceName: s2-sample-did
  chaincode:
    url: http://localhost:9090

s2:
  storming:
    enable: false

debug: true