version: "3.2"
services:
  redis:
    image: redis/redis-stack:6.2.2-v2-edge
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
