version: "3.3"

services:
  Organization:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - "127.0.0.1:27017:27017"
#    volumes:
#      - ../backup/dev/opt/volumes/mongodb/data/:/data/db/
