spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost/admin
      auto-index-creation: true
  rsocket:
    server:
      port: 7000
      transport: websocket
      mapping-path: /rsocket

s2:
  storming:
    enable: false
  ssm:
    enable: true
    baseUrl: http://localhost:9090
    signer:
      user:
        name: adam
        key: user/adam
      admin:
        name: ssm-admin
        key: user/adam

logging:
  level:
    io.rsocket.FrameLogger: DEBUG
    org.springframework.boot.rsocket: DEBUG