name: Dev

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    types: [opened, synchronize, labeled, ready_for_review]
  push:
    branches:
      - main
      - 'release/*'

jobs:
  libs:
    uses: komune-io/fixers-gradle/.github/workflows/make-jvm-workflow.yml@main
    permissions:
      contents: read
      packages: write
    with:
      make-file: 'infra/make/libs.mk'
    secrets:
      FIXERS_PUBLISH_SIGNING_GPG_KEY: ${{ secrets.FIXERS_PUBLISH_SIGNING_GPG_KEY }}
      FIXERS_PUBLISH_SIGNING_GPG_KEY_PASSWORD: ${{ secrets.FIXERS_PUBLISH_SIGNING_GPG_KEY_PASSWORD }}
      FIXERS_PUBLISH_GITHUB_USERNAME: ${{ github.actor }}
      FIXERS_PUBLISH_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FIXERS_PUBLISH_MAVEN_CENTRAL_USERNAME: ${{ secrets.FIXERS_PUBLISH_MAVEN_CENTRAL_USERNAME }}
      FIXERS_PUBLISH_MAVEN_CENTRAL_PASSWORD: ${{ secrets.FIXERS_PUBLISH_MAVEN_CENTRAL_PASSWORD }}
      FIXERS_SONAR_TOKEN: ${{ secrets.FIXERS_SONAR_TOKEN }}

  sec:
    needs: libs
    uses: komune-io/fixers-gradle/.github/workflows/sec-workflow.yml@main
    permissions:
      contents: write
      pull-requests: read
    secrets:
      FIXERS_SONAR_TOKEN: ${{ secrets.FIXERS_SONAR_TOKEN }}
