name: Release Package

on: [push]
#on:
#  push:
#    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Setup Maven Github Pkg
        run: |
          cp ./gradle/repository.gradle.kts ~/.gradle/init.gradle.kts
      - name: Version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Publish
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          PKG_MAVEN_USERNAME: ${{ secrets.PKG_MAVEN_USERNAME }}
          PKG_MAVEN_TOKEN: ${{ secrets.PKG_MAVEN_TOKEN }}
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          echo "Publishing version ${VERSION}"
          VERSION=${VERSION} make publish-libs

