name: Sec

on:
  pull_request:
    types: [opened, synchronize, labeled]
  push:
    branches:
      - main
      - 'release/*'

jobs:
  Sec:
    uses: komune-io/fixers-gradle/.github/workflows/sec-workflow.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: write
      pull-requests: read
      security-events: write
      packages: read